name: steel-forecasting-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7    
  - pip
  - pandas
  - scikit-learn
  - mlflow=2.19.0    
  - pip:
    - numpy
    - matplotlib
    - seaborn